### ISSUE TITLE
missing files for iOS 12.4

### ISSUE THREAD

**Issue by code-bryan** [Yatko/iOS-device-support-files#13]
Hi, i see that is missing the IOS 12.4 dmg

**Comment by jitendraF5buddy** [comment]
Yes I got same issue for missing IOS 12.4 dmg

**Comment by code-bryan** [comment]
I found a workaround that helps me if you need it @jitendraF5buddy https://stackoverflow.com/questions/57193651/ios-12-4-device-support-files-for-xcode,

**Comment by ica4c** [comment]
#14 IOS 12.4 support files added
