### ISSUE TITLE
13.2 (17B5077a)

### ISSUE THREAD

**Issue by vikdenic** [Yatko/iOS-device-support-files#19]
None of the 13.2 files provided are allowing Xcode 10.2.1 to install on to my iOS 13.2 (17B5077a) device. Any chance compatible files for this case are available?

**Comment by ica4c** [comment]
Last available xcode beta only have 17B5068e build. Best thing to do is to wait until Apple release the next update for xcode or downgrade to previous version of ios.

**Comment by ica4c** [comment]
@vikdenic If you're still looking I've just uploaded 17B80 device support files from fresh xcode release. 17B5077a should be covered in it too.
