### ISSUE TITLE
Please add iOS 13.2 (17B84) support files for Xcode 11

### ISSUE THREAD

**Issue by shibin919** [Yatko/iOS-device-support-files#22]

**Comment by ica4c** [comment]
There was no such build in public XCode builds as far as I remember. I've uploaded 17B102(#21) earlier this day didn't it work for you?

**Comment by rainypixels** [comment]
Unfortunately I'm hitting the same thing...

**Comment by akazadd** [comment]
same issue

**Comment by Yatko** [comment]
13.2 (17B80) included by @ica4c about a month ago
