### ISSUE TITLE
Please add iOS 13.3

### ISSUE THREAD

**Issue by nocodedweb** [Yatko/iOS-device-support-files#23]

**Comment by ica4c** [comment]
13.3 SDK haven't been released yet. As far as I remember.

**Comment by ChengzhiHuang** [comment]
I have a crash on iOS13.3, also hope to see 13.3 beta2.

**Comment by Yatko** [comment]
iOS 13.3 (17C54) is out, still no SDK included

**Comment by ica4c** [comment]
iOS 13.3 works just ok with latest iOS 13.2 SDK. Made a copy of 17B102 and named it 13.3 just to make it more obvious(#25).
