### ISSUE TITLE
Please add iOS 13.4.5 (17F5044d)

### ISSUE THREAD

**Issue by huobazi** [Yatko/iOS-device-support-files#30]
**Could not locate device support files.**

```
This iPhone 6s is running iOS 13.4.5 (17F5044d), which may not be supported by this version of Xcode. An updated version of Xcode may be found on the App Store or at developer.apple.com.
```

**Comment by ica4c** [comment]
Apple haven't released this sdk yet. We try to deploy new versions as soon as they were released so stay tuned I'll link PR to this issue once it will be available.

**Comment by ica4c** [comment]
Hey @huobazi. Just pushed newly release 13.5 beta build. Check it out #31.
