### ISSUE TITLE
12.4 file is ambigous

### ISSUE THREAD

**Issue by SureshKumarShukla79** [Yatko/iOS-device-support-files#32]
Please add which version and code is supported by 12.4 device support files.

I have iPhone 6 with 12.4.5 with 16G161 Would this work?
I use Xcode 10.1 + 2011 iMac for development. 

Thanks for the useful project.

**Comment by ica4c** [comment]
Hello @SureshKumarShukla79. Added missing version tags for 12.3, 12.4(#34) and 13.0(#33)
