### ISSUE TITLE
12.4.5  or 12.4.6 - requested

### ISSUE THREAD

**Issue by SureshKumarShukla79** [Yatko/iOS-device-support-files#35]
If possible pls get 12.4.5 or 12.4.6 (latest) device support files.
They are last versions for iPhone 6 model.
They would be useful to many users.

**Comment by ica4c** [comment]
Hi @SureshKumarShukla79. Unfortunately it's a really old sdks and I didn't find anywhere on the web. So I guess only option is to use latest 12.4(16G77) release.
