### ISSUE TITLE
iOS 12.0 (16A5345f)

### ISSUE THREAD

**Issue by jookovjook** [Yatko/iOS-device-support-files#4]
Really appreciate your contribution, bros)
I'll be grateful if You can add iOS 12.0 (16A5345f)

**Comment by Yatko** [comment]
Not sure how to retrieve 16A5308e ( mentioned by @BaherHosni #2 ) and 16A5345f, Xcode betas are coming with the attached iOS device support files. Will try to better figure it out for next time!
