### ISSUE TITLE
iOS-device-support-files for 13.6(17G68)

### ISSUE THREAD

**Issue by pradweep** [Yatko/iOS-device-support-files#45]
HI @Yatko ,

Can you please provide the device support files for 13.6(17G68) version.

Thanks & Cheers,
Pradeep Kumar.M

**Comment by ica4c** [comment]
Hello @pradweep. Unfortunately latest version existing in the public SDK is 17G64 which can be found in this repo(#51). Everything greater than either in-exists or unavailable for public usage. Keep tracking for updates we'll add it here as soon as it will be available.
