### ISSUE TITLE
13.6.1 (17G80)

### ISSUE THREAD

**Issue by bamwu** [Yatko/iOS-device-support-files#49]

**Comment by bamwu** [comment]
Thanks.

**Comment by bamwu** [comment]
Were you able to locate the 13.6.1 support files? This was marked closed last week, but 13.6.1 still isn't included.

Thanks.

**Comment by ica4c** [comment]
Hello @bamwu. Sorry for the delayed answer. I guess someone from the team closed this without leaving any commentary by accident. 
Unfortunately latest version existing in the public SDK is 17G64 which can be found in this repo(#51). Everything greater than this either in-exists or unavailable for public usage. Keep tracking for updates we'll add it here as soon as it will be available.
