### ISSUE TITLE
Upload Archives 

### ISSUE THREAD

**Issue by jay58** [Yatko/iOS-device-support-files#53]
Upload archives instead of folder so the people can download particular support file and in this way they don't have to clone or download the whole repo.

**Comment by ica4c** [comment]
Hey @jay58. Good idea actually.

**Comment by Yatko** [comment]
> Upload archives instead of folder so the people can download particular support file and in this way they don't have to clone or download the whole repo.

Great idea @jay58 ... [iOS 15 Beta device support files - iOS 15.0 (.zip archive)](https://github.com/Yatko/iOS-device-support-files/blob/master/15.0%20-%20iOS%2015%20Beta%20device%20support%20files.zip)
