### ISSUE TITLE
Problem with last iOS 14 device support signature

### ISSUE THREAD

**Issue by user1man** [Yatko/iOS-device-support-files#54]
It opens in viewer, so I can't download file to add to Xcode. Earlier I can do it.

**Comment by ica4c** [comment]
Hey @user1man. You mean on github? If so you can click `Raw` button on it's toolbar. It will redirect you on a source file.

**Comment by jay58** [comment]
@user1man You need to clone the repository to download the files. Latest 14.0 (18A5357e) Beta version is working for me.

[Archive Upload](https://github.com/Yatko/iOS-device-support-files/issues/53), I have added this issue. It will solve future download problems.

**Comment by user1man** [comment]
> Hey @user1man. You mean on github? If so you can click `Raw` button on it's toolbar. It will redirect you on a source file.

In last two betas github on web open signature with quick viewer. In older versions I can tap Raw because quick view wasn't support. Viewer looks like this.![image](https://user-images.githubusercontent.com/33625167/91703166-71752580-eb82-11ea-9ec4-25ab44ff1023.jpeg)

**Comment by user1man** [comment]
> @user1man You need to clone the repository to download the files. Latest 14.0 (18A5357e) Beta version is working for me.
> 
> 
> 
> [Archive Upload](https://github.com/Yatko/iOS-device-support-files/issues/53), I have added this issue. It will solve future download problems.

I have problems with raw download, earlier versions works, but not now.

**Comment by Yatko** [comment]
Archives will be uploaded per suggestion from @jay58
