### ISSUE TITLE
Adding the files for iOS 12.1 (16B5077c)

### ISSUE THREAD

**Issue by bloemy7** [Yatko/iOS-device-support-files#7]
Would you be able to find the files for this beta version of 12.1? Suddenly impossible to test my XCode builds on my own phone since I am running this beta version of 12.1.
You'd save my life ! Thanks.

**Comment by Yatko** [comment]
Hi, here are the [device support files for iOS 12.1](https://github.com/Yatko/iOS-device-support-files/tree/master/12.1%20(16B5059d)), the ones that came with latest Xcode. Missed the build number in your request, will try to add 16B5077c (beta 3) and 16B5068i (beta 2).
