### ISSUE TITLE
12.1 beta not working with 12.1 release

### ISSUE THREAD

**Issue by consciouscoder** [Yatko/iOS-device-support-files#8]
The 12.1 beta support files do not seem to be working with 12.1 release. Can we get an update to the support files for 12.1 release please?

**Comment by Christopher876** [comment]
Those files do work as I have been using them on my iPad on 12.1. As for if you want to use those files, just download the latest Xcode and then show the contents file, and then go to the iPhone support files folder and copy the support files you want.
